// Nix's head as the site mark: cropped from the waving pose, then
//  - src/assets/nix/nix-head.png   the navbar logo (he peeks up from the bar's bottom rule)
//  - public/favicon-*.png, public/apple-touch-icon.png   a plaster badge he peeks into
// Run after `pnpm nix` (or on its own): pnpm icons
import sharp from 'sharp';
import { fileURLToPath } from 'node:url';
import { setPngText } from './lib/png-text.mjs';

const ORIGIN =
  'ORIGIN: derived by scripts/icons.mjs from src/assets/nix/nix-wave.png (head crop; badge composited on a plaster tile). Nix sheet generated by the owner with nano-banana.';

const root = fileURLToPath(new URL('../', import.meta.url));
const wave = root + 'src/assets/nix/nix-wave.png';

// the head sits above y≈352 in the waving pose; below that the body starts
const { data: head, info } = await sharp(wave)
  .extract({ left: 30, top: 0, width: 432, height: 352 })
  .trim({ threshold: 1 })
  .png()
  .toBuffer({ resolveWithObject: true });

await sharp(head)
  .png({ compressionLevel: 9 })
  .toFile(root + 'src/assets/nix/nix-head.png');
setPngText(root + 'src/assets/nix/nix-head.png', 'impeccable:prompt', ORIGIN);
console.log(`icons: head ${info.width}×${info.height}`);

// the badge: a plaster tile with an ink edge; the head rises from its bottom edge
const PLASTER = '#e8ebe1';
const INK = '#23261e';
async function badge(size, file) {
  const S = 512;
  const edge = 26;
  const r = 118;
  // big enough that the screen face reads at 16px; the face is centred, the cut edge falls outside
  const w = 640;
  const h = Math.round((w / info.width) * info.height);
  const x = Math.round(S / 2 - 0.56 * w);
  const y = Math.max(S - edge - h + 10, Math.round(S * 0.6 - 0.62 * h));
  const b64 = head.toString('base64');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">
    <defs><clipPath id="c"><rect x="${edge / 2}" y="${edge / 2}" width="${S - edge}" height="${S - edge}" rx="${r}"/></clipPath></defs>
    <rect x="${edge / 2}" y="${edge / 2}" width="${S - edge}" height="${S - edge}" rx="${r}" fill="${PLASTER}"/>
    <g clip-path="url(#c)"><image x="${x}" y="${y}" width="${w}" height="${h}" xlink:href="data:image/png;base64,${b64}"/></g>
    <rect x="${edge / 2}" y="${edge / 2}" width="${S - edge}" height="${S - edge}" rx="${r}" fill="none" stroke="${INK}" stroke-width="${edge}"/>
  </svg>`;
  await sharp(Buffer.from(svg)).resize(size, size).png({ compressionLevel: 9 }).toFile(root + file);
  setPngText(root + file, 'impeccable:prompt', ORIGIN);
  console.log(`icons: ${file}`);
}
await badge(32, 'public/favicon-32.png');
await badge(96, 'public/favicon-96.png');
await badge(180, 'public/apple-touch-icon.png');
await badge(512, 'public/icon-512.png');
