// Nix's head as the site mark, from the front-facing head pose (nix-head.png, cut by
// scripts/nix-sheets.mjs): public/favicon-*.png and public/apple-touch-icon.png are a plaster
// badge with an ink edge and the head centred inside. The navbar uses nix-head.png directly.
// Run after the sheets are cut: pnpm icons
import sharp from 'sharp';
import { fileURLToPath } from 'node:url';
import { setPngText } from './lib/png-text.mjs';

const ORIGIN =
  'ORIGIN: composited by scripts/icons.mjs from src/assets/nix/nix-head.png on a plaster tile. Nix sheets generated by the owner with nano-banana.';
const root = fileURLToPath(new URL('../', import.meta.url));
const { data: head, info } = await sharp(root + 'src/assets/nix/nix-head.png').png().toBuffer({ resolveWithObject: true });

// the badge: a plaster tile with an ink edge, the head centred in it
const PLASTER = '#e8ebe1';
const INK = '#23261e';
async function badge(size, file) {
  const S = 512;
  const edge = 26;
  const r = 118;
  // big enough that the screen face reads at 16px
  const w = 420;
  const h = Math.round((w / info.width) * info.height);
  const x = Math.round((S - w) / 2);
  const y = Math.round((S - h) / 2) + 8;
  const b64 = head.toString('base64');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">
    <defs><clipPath id="c"><rect x="${edge / 2}" y="${edge / 2}" width="${S - edge}" height="${S - edge}" rx="${r}"/></clipPath></defs>
    <rect x="${edge / 2}" y="${edge / 2}" width="${S - edge}" height="${S - edge}" rx="${r}" fill="${PLASTER}"/>
    <g clip-path="url(#c)"><image x="${x}" y="${y}" width="${w}" height="${h}" xlink:href="data:image/png;base64,${b64}"/></g>
    <rect x="${edge / 2}" y="${edge / 2}" width="${S - edge}" height="${S - edge}" rx="${r}" fill="none" stroke="${INK}" stroke-width="${edge}"/>
  </svg>`;
  await sharp(Buffer.from(svg)).resize(size, size).png({ compressionLevel: 9 }).toFile(root + file);
  setPngText(root + file, 'impeccable:prompt', ORIGIN);
  console.log(`icons: ${file}`);
}
await badge(32, 'public/favicon-32.png');
await badge(96, 'public/favicon-96.png');
await badge(180, 'public/apple-touch-icon.png');
await badge(512, 'public/icon-512.png');
